name: CI - docker buildx cross-platform
on:
  push:
    workflow_dispatch:
    branches:
      - master
      - develop
    pull_request:
      - master
    tags:
      - "v*"
    schedule:
      - cron: "10 1 * * 0"

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install -y php php-mbstring php-xmlrpc php-soap php-gd php-xml php-cli php-zip
          sudo apt install -y curl
          curl -sS https://getcomposer.org/installer | php
          mkdir -p $(pwd)/.build/art_of_wifi/calls
          while read -r line;
          do
            alias="$(echo $line | sed -e 's/\(\)//')"
            echo "Creating $alias"
            f="$(echo $line | sed -e 's/\(\)/.php/')"
            file=$(pwd)/.build/art_of_wifi/calls/$line.php
            touch $file
            cat $(pwd)/src/template/api_call.tpl | sed -e "s/<call>/$line/" > $file
          done < $(pwd)/config/api_calls.txt
          ls $(pwd)/.build/art_of_wifi/calls/

      - name: Set up Qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: tagging
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=raw,value=develop,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
            type=ref,event=tag
            type=schedule
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Login to Docker hub
        if: github.event.name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
         
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/docker/Dockerfile.client
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'workflow_dispatch' }}
          tags: ${{ steps.tagging.outputs.tags }}
          labels: ${{ steps.tagging.outputs.labels }}
          build-args: APP_NAME=art_of_wifi
