name: CI - docker buildx cross-platform
on:
  push:
    branches:
      - master
    pull_request:
      - master
    tags:
      - "v*"
    schedule:
      - cron: "10 1 * * 0"

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: tagging
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=raw,value=develop,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
            type=ref,event=tag
            type=schedule
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Login to Docker hub
        if: github.event.name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: {context}/src/docker/Dockerfile.client
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'workflow_dispatch' }}
          tags: ${{ steps.tagging.outputs.tags }}
          labels: ${{ steps.tagging.outputs.labels }}
          build-args:
          - APP_NAME=art-of-wifi
