name: CI - docker buildx cross-platform
on:
  push:
    workflow_dispatch:
    branches:
      - master
      - develop
    pull_request:
      - master
    tags:
      - "v*"
    schedule:
      - cron: "10 1 * * 0"

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: tagging
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=raw,value=develop,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
            type=ref,event=tag
            type=schedule
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Login to Docker hub
        if: github.event.name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Prepare environment
        run: |
          mkdir .build
          mkdir .build/art_of_wifi
          mkdir .build/art_of_wifi/calls
          app_name=art_of_wifi
          settings="config/api_calls.txt"
          dir=".build/$app_name/calls"
          api_tpl="src/template/api_call.tpl"
          config_template="src/template/api_config.tpl"
          docker run --rm -it -v ".build/art_of_wifi/calls:/app" composer/composer require art-of-wifi/unifi-api-client
          cp src/template/api_config.tpl .build/art_of_wifi/calls/config.php
          while read line;
          do
          echo $line | sed -e 's/()//'
          alias="$(echo $line | sed -e 's/()//')"
          settings="$(echo $line | sed -e 's/()/.php/')"
          file=$dir/$settings
          touch $file
          cat $api_tpl | sed -e "s/<call>/$line/" > $file
          done < config/api_calls.txt
         
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/docker/Dockerfile.client
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'workflow_dispatch' }}
          tags: ${{ steps.tagging.outputs.tags }}
          labels: ${{ steps.tagging.outputs.labels }}
          build-args: APP_NAME=art_of_wifi
